spring.application.name=chatroom
spring.datasource.url = jdbc:mysql://localhost:3306/chatroom?autoReconnect=true&useSSL=false
spring.datasource.username = root
spring.datasource.password = root

spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.hibernate.ddl-auto = update

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

jwt.secret= c2xvZ1NlY3IxMiQ=fp5ovitomkornicmll
jwt.header: X-Auth
jwt.expiration: 86400000